version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DIRECTUS_URL=http://directus:8055
    depends_on:
      - directus

  directus:
    build: ./directus
    ports:
      - "8055:8055"
    environment:
      - NODE_ENV=development
      - KEY=dev-secret-key
      - ADMIN_EMAIL=admin@dev.com
      - ADMIN_PASSWORD=devpassword
      - DB_CLIENT=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=directus_dev
    volumes:
      - ./directus/uploads:/directus/uploads
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=directus
      - POSTGRES_PASSWORD=directus
      - POSTGRES_DB=directus_dev
    volumes:
      - ./pgdata-dev:/var/lib/postgresql/data